### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by chaohe1998** [jkk-research/urban_road_filter#11]
Hello, I follow the steps to generate this error. How should I solve it? Thanks 
`Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
urban_road_filter/CMakeFiles/lidar_road.dir/build.make:75: recipe for target 'urban_road_filter/CMakeFiles/lidar_road.dir/src/lidar_segmentation.cpp.o' failed
make[2]: *** [urban_road_filter/CMakeFiles/lidar_road.dir/src/lidar_segmentation.cpp.o] Error 4
make[2]: *** 正在等待未完成的任务....
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
urban_road_filter/CMakeFiles/lidar_road.dir/build.make:131: recipe for target 'urban_road_filter/CMakeFiles/lidar_road.dir/src/z_zero_method.cpp.o' failed
make[2]: *** [urban_road_filter/CMakeFiles/lidar_road.dir/src/z_zero_method.cpp.o] Error 4
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
urban_road_filter/CMakeFiles/lidar_road.dir/build.make:89: recipe for target 'urban_road_filter/CMakeFiles/lidar_road.dir/src/main.cpp.o' failed
make[2]: *** [urban_road_filter/CMakeFiles/lidar_road.dir/src/main.cpp.o] Error 4
CMakeFiles/Makefile2:2521: recipe for target 'urban_road_filter/CMakeFiles/lidar_road.dir/all' failed
make[1]: *** [urban_road_filter/CMakeFiles/lidar_road.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
`

**Comment by horverno** [comment]
hi @chaohe1998 what's your os / ROS version? what are the steps to reproduce this? have you tried `catkin clean` and `catkin build urban_road_filter` again?

**Comment by horverno** [comment]
hi @chaohe1998  did you manage to solve it? If yes the issue can be closed now. Feel free to re-open if needed.
