### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DbzXexpert** [jkk-research/urban_road_filter#12]
How can we use this algorithm on single pcd files?

**Comment by horverno** [comment]
hi @DbzXexpert 
i assume ROS is installed in this case the easiest way is to publish your pcd file as a pointcloud topic e.g.
```
rosrun pcl_ros pcd_to_pointcloud your_pcd_file.pcd _frame_id:=left_os1/os1_lidar _interval:=0.1
```
the topic name will be: `/cloud_pcd`
read more: http://wiki.ros.org/pcl_ros

**Comment by horverno** [comment]
hi @DbzXexpert did you manage to solve it? If yes the issue can be closed now. (It will be closed also if stale / inactive)
