### ISSUE TITLE
Here should be [rep-1]

### ISSUE THREAD

**Issue by kechaofan** [jkk-research/urban_road_filter#13]
https://github.com/jkk-research/urban_road_filter/blob/334338f294155344cb0d5f2b7fedcfee0007970e/src/star_shaped_search.cpp#L58

**Comment by csaplaci** [comment]
you are right

thank you for the feedback - it will be corrected soon

(actually it is a remnant of a proposed but later abandoned feature/solution to extract points from adjacent detection beams if they are overlapping close to the pole of the coordinate system - would they have insufficient data as the preliminary filter would cut them off in a circular sector shape, leaving only a fraction of the points at disposal for detection...

...the problem itself did not arise though, so the algorithm never got implemented - therefore the code snippet is obsolete and will be disposed of accordingly)

i hope it did not cause any significant problems
