### ISSUE TITLE
About run-time

### ISSUE THREAD

**Issue by liuqijun1** [jkk-research/urban_road_filter#14]
Hello，how can I test the runtime of a frame？check the topic frequency or need clock？ how should I solve it? Thanks

**Comment by horverno** [comment]
hello @liuqijun1 
It depends what are you exactly curious about.
If you run the demo and you just need check the frequency, simply type: ` rostopic hz /urban_road_filter/curb` (the average rate should be around 20 Hz).
Does this solution works for you?

**Comment by liuqijun1** [comment]
I'll check. Thank you!
