### ISSUE TITLE
Facing issues while using different dataset

### ISSUE THREAD

**Issue by arzooqureshi** [jkk-research/urban_road_filter#17]
I am trying to convert some standard datasets to robag file and use them. But the ROS topics my bag files are far less and different than the ROS topics in the data given in repository. How to make this work?

**Comment by horverno** [comment]
Changing the topic name and the frame is easy, just give it in you launch file e.g:

``` xml
  <node name="urban_road_filt" pkg="urban_road_filter" type="lidar_road" output="screen">
      <param name="topic_name" value="/left_os1/os1_cloud_node/points"/>
      <param name="fixed_frame" value="left_os1/os1_lidar"/>
  </node>
```

If you are struggling with basic ROS concepts i suggest to have a look at the tutorials: http://wiki.ros.org/ROS/Tutorials

I will close the issue now, if you still have problems with this issue, feel free to reopen it.
