### ISSUE TITLE
Velodyne-32 Lidar on Husky

### ISSUE THREAD

**Issue by KshitizKumarGupta** [jkk-research/urban_road_filter#18]
Hey, I am facing problem with parameter tuning. I am trying with a single velodyne-32 channel lidar mounted on Husky rover. The code crashes on changing the parameters through the parameter-window occurs along with rviz. 
Can u suggest something??

**Comment by horverno** [comment]
https://github.com/jkk-research/urban_road_filter/discussions/16#discussioncomment-5919328_
