### ISSUE TITLE
  I would like to know if this algorithm can still work for single frame point clouds synthesized by three mechanical radars

### ISSUE THREAD

**Issue by FengYuQ** [jkk-research/urban_road_filter#20]
I now want to perform ground removal on the synthesized point cloud, and I am not sure if this algorithm can work in the synthesized point cloud. Mechanical radars are all mounted on cars, with one radar overhead and two radars on the side

**Comment by horverno** [comment]
I don't think it will work on radars. Even on solid-state LIDAR there are limitations. You can read about the limitations in Conclusions and Future Work section of the paper.

**Comment by FengYuQ** [comment]
> I don't think it will work on radars. Even on solid-state LIDAR there are limitations. You can read about the limitations in Conclusions and Future Work section of the paper.

Sorry, this is my pen mistake. What I mean is a point cloud composed of three rotating mechanical Lidar

**Comment by horverno** [comment]
That could work theoretically. Try **only** enabling the `star_shaped_method`. 
`x_zero_method` and `x zero method` use channel information of a single LIDAR, which is not relevant if the pointcloud is merged from 3 LIDARS.

**Comment by FengYuQ** [comment]
So I still have a question is that if I use the point cloud of merged and what the value of channel should I have set?

**Comment by horverno** [comment]
As mentioned  `star_shaped_method` does not rely on channel info, so it doesn't matter.
The only problem with this approach is that it uses one method instead of three, so it won't be as accurate.
