### ISSUE TITLE
Add some usage examples

### ISSUE THREAD

**Issue by chengwei0427** [jkk-research/urban_road_filter#3]
Hi, Horvath

Great work! I'm very interested in your work. Can you add some usage demo about this work.

Thanks!

**Comment by horverno** [comment]
hi, sure, actually issue #2 will be about this

**Comment by horverno** [comment]
@chengwei0427 here is a usage example:

In a **new terminal** start roscore:
```
roscore
```
In a **new terminal** go to your bag folder (e.g. `~/Downloads`):
```
cd ~/Downloads
```
Download a sample rosbag:
``` r
wget https://laesze-my.sharepoint.com/:u:/g/personal/herno_o365_sze_hu/EYl_ahy5pgBBhNHt5ZkiBikBoy_j_x95E96rDtTsxueB_A?download=1 -O leaf-2021-04-23-campus.bag
```
Play rosbag:
``` r
rosbag play -l ~/Downloads/leaf-2021-04-23-campus.bag
```
In a **new terminal** start the `urban_road_filter` node, `rviz` and `rqt_reconfigure` with roslaunch:
```
roslaunch urban_road_filter demo1.launch
```

**Comment by chengwei0427** [comment]
good, I'll check and update. Thank you!

**Comment by chengwei0427** [comment]
Another question, Does this method support 16-line or 32-line lasers? If yes, what parameters need to be adjusted?
thanks again.

**Comment by chengwei0427** [comment]
> @chengwei0427 here is a usage example:
> 
> In a **new terminal** start roscore:
> 
> ```
> roscore
> ```
> 
> In a **new terminal** go to your bag folder (e.g. `~/Downloads`):
> 
> ```
> cd ~/Downloads
> ```
> 
> Download a sample rosbag:
> 
> ```r
> wget https://laesze-my.sharepoint.com/:u:/g/personal/herno_o365_sze_hu/EYl_ahy5pgBBhNHt5ZkiBikBoy_j_x95E96rDtTsxueB_A?download=1 -O leaf-2021-04-23-campus.bag
> ```
> 
> Play rosbag:
> 
> ```r
> rosbag play -l ~/Downloads/leaf-2021-04-23-campus.bag
> ```
> 
> In a **new terminal** start the `urban_road_filter` node, `rviz` and `rqt_reconfigure` with roslaunch:
> 
> ```
> roslaunch urban_road_filter demo1.launch
> ```

It's amazing on my test data.

**Comment by horverno** [comment]
@chengwei0427 thanks for the feedback
#1 will be about the refactor and english comments in the code @dobaybalazs is assigned to this task

In the meantime you can read the published paper as a [pdf](https://github.com/jkk-research/urban_road_filter/blob/main/docs/sensors_paper_urban_road_filter.pdf). It describes the algorithm in detail.
 
> It's amazing on my test data.
> But the code is hard to read,Can you add some English annotation?

**Comment by horverno** [comment]
The original algorithm was developed for 16 channel LIDAR, so probably it will work (unless we have done something what breaks this compatibility). The `star_shaped_method` has the least limitations, so try to disable `x_zero_method` and `x_zero_method` in the rqt_reconfigure window. The `star_shaped_method` also works on special pointclouds (e.g. provided by a solid state LIDAR).

This issue is about the usage examples, so I will close this now, but feel free to open another issue about the compatibility if needed.

**Comment by chengwei0427** [comment]
My questions are well solved. Thank you for your patient reply. 
Thanks again.

**Comment by juliangaal** [comment]
> The original algorithm was developed for 16 channel LIDAR

Can you share some good parameters for, let's say, a VLP16?

**Comment by horverno** [comment]
Currently I don't have acees to VLP16, but as mentioned maybe you can try to adjust the `interval` param which adjusts the LIDAR's vertical resolution. Try it in a launch file, but as far as i remember rqt_reconfigure may also works.

Maybe @csaplaci also can suggest something.
