### ISSUE TITLE
If the given dataset have a preprocessing?

### ISSUE THREAD

**Issue by LuYoKa** [jkk-research/urban_road_filter#7]
Thanks for your great work! I try to do some experiment on kitti dataset. But I found it does not have the same effect as yours. The blue marks, as shown in the following image, are false positive.  I want to wonder if the given dataset have a preprocessing?  ![img](https://natsu-akatsuki.oss-cn-guangzhou.aliyuncs.com/img/86ead89ee362210c405937ff03b90cc.jpg)

**Comment by horverno** [comment]
hi @LuYoKa 

Our dataset is not preprocessed. Try to tune the params according the publication. Hope this helps.

![image](https://user-images.githubusercontent.com/11504709/154946330-64d854f9-fc9f-4cfd-b7ed-4ca0c3106ba2.png)

**Comment by dobaybalazs** [comment]
> Thanks for your great work! I try to do some experiment on kitti dataset. But I found it does not have the same effect as yours. The blue marks, as shown in the following image, are false positive. I want to wonder if the given dataset have a preprocessing? ![img](https://camo.githubusercontent.com/4b72b0d3fd8758fd466dbba2f748bed4eb542fbde0e3e329ff88f2fd200db70f/68747470733a2f2f6e617473752d616b617473756b692e6f73732d636e2d6775616e677a686f752e616c6979756e63732e636f6d2f696d672f383665616438396565333632323130633430353933376666303362393063632e6a7067)

Hello @LuYoKa 
Have you changed the interval parameter?

**Comment by crankler** [comment]
Hi, same question, @LuYoKa , @dobaybalazs 
I tried and can't get a good params cfg here,  have you succeed to split the curb in kitti dataset?

**Comment by crankler** [comment]
Yes, thank you for your reply, I test on kitti odom dataset 09, the link is here:  http://www.cvlibs.net/datasets/kitti/eval_odometry.php

Recently, I have tested a few params, but it's not performer well, so I try to transform your "x_zero_method" and "z_zero_method"  method in my code. For the terrain have slope and cross, so I still test different method to get a good results.
It's interesting to see you can show in different dataset, 
best wishes!

**Comment by dobaybalazs** [comment]
> Yes, thank you for your reply, I test on kitti odom dataset 09, the link is here: http://www.cvlibs.net/datasets/kitti/eval_odometry.php
> 
> Recently, I have tested a few params, but it's not performer well, so I try to transform your "x_zero_method" and "z_zero_method" method in my code. For the terrain have slope and cross, so I still test different method to get a good results. It's interesting to see you can show in different dataset, best wishes!

It is interesting indeed, and it is awesome that you have been experimenting with the code itself. Thank you for sending the link, I will test the algorithms on the dataset myself and see if I can manage to find the optimal params. Until then, best wishes to you as well.
